---
- name: Setup project bastion host
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Import VPC setup variable
      ansible.builtin.include_vars: vars/bastion_setup

    - name: Import VPC output variables
      ansible.builtin.include_vars: vars/output_vars

    - name: Create a new ec2 key pair
      amazon.aws.ec2_key:
        name: pro-key
        region: "{{ region }}"
      register: keyout

    - name: Save private key into bastion_key.pem
      ansible.builtin.copy:
        content: "{{ keyout.key.private_key }}"
        dest: "./bastion-key.pem"
        mode: "0600"
      when: keyout.changed

    - name: Create security group for bastion host
      amazon.aws.ec2_security_group:
        name: Bastion-host-SG
        description: Allow port 22 from everywhere and all ports within SG
        region: "{{ region }}"
        vpc_id: "{{ vpcid }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{ MYIP }}"
      register: bastionsg_out

    - name: Creating Bastion host
      amazon.aws.ec2_instance:
        key_name: pro-key
        region: "{{ region }}"
        instance_type: t2.micro
        image: "{{ bastion_ami }}"
        wait: true
        wait_timeout: 300
        instance_tags:
          Name: "Bastion Host"
          Project: Ans_AWS_vpc
          Owner: Maybelle
        exact_count: 1
        count_tag:
          Name: "Bastion Host"
          Project: Ans_AWS_vpc
          Owner: Maybelle
        group_id: "{{ bastionsg_out.group_id }}"
        vpc_subnet_id: "{{ pubsub1id }}"
      register: bastionhost_out
