---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Import VPC variables
      include_vars: vars/vpc_setup

    - name: Create vprofile VPC
      ec2_vpc_net:
        name: "{{ vpc_name }}"
        cidr_block: "{{ vpcCidr }}"
        region: "{{ region }}"
        dns_support: true
        dns_hostnames: true
        tenancy: default
        state: "{{ state }}"
      register: vpcout

#    - debug:
#        var: vpcout

    - name: Create public subnet 1 in zone 1
      ec2_vpc_subnet:
        vpc_id: "{{ vpcout.vpc.id }}"
        region: "{{ region }}"
        az: "{{ zone1 }}"
        state: "{{ state }}"
        cidr: "{{ PubSub1Cidr }}"
        map_public: true
        resource_tags:
          Name: vprofile-pubsub1
      register: pubsub1_out

    - name: Create public subnet 2 in zone 2
      ec2_vpc_subnet:
        vpc_id: "{{ vpcout.vpc.id }}"
        region: "{{ region }}"
        az: "{{ zone2 }}"
        state: "{{ state }}"
        cidr: "{{ PubSub2Cidr }}"
        map_public: true
        resource_tags:
          Name: vprofile-pubsub2
      register: pubsub2_out

    - name: Create public subnet 3 in zone 3
      ec2_vpc_subnet:
        vpc_id: "{{ vpcout.vpc.id }}"
        region: "{{ region }}"
        az: "{{ zone3 }}"
        state: "{{ state }}"
        cidr: "{{ PubSub3Cidr }}"
        map_public: true
        resource_tags:
          Name: vprofile-pubsub3
      register: pubsub3_out

    - debug:
        var: pubsub2_out

    # - name: Create public subnet 4 in zone 4
    #   ec2_vpc_subnet:
    #     vpc_id: "{{ vpcout.vpc.id }}"
    #     region: "{{ region }}"
    #     az: "{{ zone1 }}"
    #     state: "{{ state }}"
    #     cidr: "{{ PubSub4Cidr }}"
    #     map_public: true
    #     resource_tags:
    #       Name: vprofile-pubsub4
    #   register: pubsub4_out

    # - name: Create public subnet 5 in zone 5
    #   ec2_vpc_subnet:
    #     vpc_id: "{{ vpcout.vpc.id }}"
    #     region: "{{ region }}"
    #     az: "{{ zone2 }}"
    #     state: "{{ state }}"
    #     cidr: "{{ PubSub1Cidr }}"
    #     map_public: true
    #     resource_tags:
    #       Name: vprofile-pubsub5
    #   register: pubsub5_out

    # - name: Create public subnet 6 in zone 6
    #   ec2_vpc_subnet:
    #     vpc_id: "{{ vpcout.vpc.id }}"
    #     region: "{{ region }}"
    #     az: "{{ zone3 }}"
    #     state: "{{ state }}"
    #     cidr: "{{ PubSub1Cidr }}"
    #     map_public: true
    #     resource_tags:
    #       Name: vprofile-pubsub6
    #   register: pubsub6_out
